---
title: "Días grado"
lang: es
author: "M. Abel Herrera"
format: html
editor: visual
execute:
  echo: false
  warning: false
  message: false
---

# Reporte: Temperatura y Días grado

## Gap-filling de temperatura diaria

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

library(fs)
library(readr)
library(dplyr)
library(lubridate)
library(tidyr)
library(stringr)
library(tidyverse)
library(scales)
library(readxl)
library(cowplot)
library(ggpubr)

data_temp <- read_rds('C:/Hemera/anillos/data/data_processed/temperatura.rds') |>
  mutate(fecha = as.Date(fecha)) |>
  group_by(sitio,temporada,fecha) |>
  summarise(tmin = min(tmin,na.rm=F),
            tmax = max(tmax,na.rm=F),
            tavg = mean(tavg,na.rm=F)) |>
  ungroup()

data_fill <- read_rds('C:/Hemera/anillos/data/data_processed/temperatura_fill.rds')

data_fill_gaps <- data_fill |>
  left_join(data_temp, by = c('sitio','temporada','fecha')) |>
  filter((sitio == 'rio_claro' & between(fecha, as.Date('2022-08-23'), as.Date('2022-09-02'))) |
           (sitio == 'la_esperanza' & between(fecha, as.Date('2023-08-14'), as.Date('2023-08-17'))))

data_fill |>
  select(-tmin,-tmax,-tavg) |>
  left_join(data_temp, by = c('sitio','temporada','fecha')) |>
  pivot_longer(cols = c('tmin','tmax'), values_to = 't', names_to = 'variable') |>
  ggplot(aes(fecha,t,color = variable)) +
  geom_line() +
  facet_grid(sitio ~temporada, scales = 'free_x', labeller = as_labeller(c('2022-2023' = 'Temporada 2022-2023',
                                                                           '2023-2024' = 'Temporada 2023-2024',
                                                                           'la_esperanza' = 'La Esperanza',
                                                                           'rio_claro' = 'Rio Claro'))) +
  scale_color_manual(values = c('blue3','green3')) +
  geom_line(data = data_fill_gaps, aes(fecha,tmin.x), color = 'red3', linetype = 2) +
  geom_line(data = data_fill_gaps, aes(fecha,tmax.x), color = 'red3', linetype = 2) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  theme_light() +
  labs(y = 'Temperatura (°C/día)',
       x = 'Meses') +
  guides(color = guide_legend(override.aes = list(size = 2.5)))

```

## Días grado

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

data_gdd <- read_rds('C:/Hemera/anillos/data/data_processed/gdd.rds') 

data_gdd |>
  mutate(fecha = case_when(temporada == '2023-2024' ~ fecha - 365,T ~ fecha),
         Curva = paste0(sitio,' (',temporada,')')) |>
  ggplot(aes(fecha,gdd_acum,color = Curva)) +
  geom_line(linewidth = 1.2) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  labs(x = 'Meses',
       y = 'Días grado',
       color = '') +
  scale_color_manual(labels=c('La Esperanza (2022-2023)', 'La Esperanza (2023-2024)',
                               'Rio Claro (2022-2023)','Rio Claro (2023-2024)'), values = hue_pal()(4)) +
  theme_light()
```

## Relación logarítmica

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true

bbch <- read_xlsx('C:/Hemera/anillos/data/data_raw/bbch.xlsx') |>
  mutate(fecha_inicial = as.Date(fecha_inicial),
         fecha_final = as.Date(fecha_final)) |>
  pivot_longer(cols = c('fecha_inicial','fecha_final'), values_to = 'fecha', names_to = 'fecha_tipo')

fechas <- bbch |>
  group_by(sitio) |>
  summarise(fecha_min = min(fecha),
            fecha_max = max(fecha)) |>
  pivot_longer(cols = c('fecha_min','fecha_max'),values_to = 'fecha',names_to = 'tipo') |>
  pull(fecha)

fechas <- list(la_esperanza = seq.Date(fechas[1],fechas[2], by = 'day'),
            rio_claro = seq.Date(fechas[3],fechas[4], by = 'day'))

data_gdd <- read_rds('C:/Hemera/anillos/data/data_processed/gdd.rds')

datos_cor <- tibble(sitio = rep(c('la_esperanza','rio_claro'),times = c(length(fechas$la_esperanza),
                                                                     length(fechas$rio_claro))),
                 fecha = as.Date(unlist(fechas))) |>
  left_join(bbch, by = c('sitio','fecha')) |>
  fill(etapa, bbch) |>
  select(-fecha_tipo) |>
  left_join(data_gdd, by = c('sitio','fecha')) |>
  select(sitio,gdd_acum,bbch) |>
  rename(gdd = gdd_acum) |>
  na.omit() |>
  mutate(gdd_log = log(gdd))

datos_le <- datos_cor |> filter(sitio == 'la_esperanza')
datos_rc <- datos_cor |> filter(sitio == 'rio_claro')

modelo_log <- nls(bbch ~ SSlogis(gdd, Asym, xmid, scal), data = datos_le)
parametros <- coef(modelo_log)
predicciones <- data.frame(gdd = seq(min(datos_le$gdd), max(datos_le$gdd), length.out = 100))
predicciones$bbch_pred <- predict(modelo_log, newdata = predicciones)

r2 <- cor(datos_le$bbch,predict(modelo_log))^2

plot_le <- ggplot(datos_le, aes(gdd,bbch)) +
  geom_point() +
  geom_line(data = predicciones, aes(gdd,bbch_pred), color = "blue", linewidth = 1) +
  annotate("text", x = 1300, y = 84, label = paste("R² =", round(r2, 2)), size = 5) +
  labs(title = "La Esperanza",
       x = "GDD",
       y = "Escala BBCH") +
  ylim(60,100) +
  theme_light()

modelo_log <- nls(bbch ~ SSlogis(gdd, Asym, xmid, scal), data = datos_rc)
parametros <- coef(modelo_log)
predicciones <- data.frame(gdd = seq(min(datos_rc$gdd), max(datos_rc$gdd), length.out = 100))
predicciones$bbch_pred <- predict(modelo_log, newdata = predicciones)

r2 <- cor(datos_rc$bbch,predict(modelo_log))^2

plot_rc <- ggplot(datos_rc, aes(gdd,bbch)) +
  geom_point() +
  geom_line(data = predicciones, aes(gdd,bbch_pred), color = "blue", linewidth = 1) +
  annotate("text", x = 1000, y = 84, label = paste("R² =", round(r2, 2)), size = 5) +
  labs(title = "Río Claro",
       x = "GDD",
       y = "Escala BBCH") +
  ylim(60,100) +
  theme_light()

plot_grid(ggdraw() + draw_label('Ajuste logarítmico BBCH vs. GDD (2022-2023)', size = 14),
                          plot_grid(plot_le,plot_rc, ncol = 2),
                          ncol = 1, rel_heights = c(.1,1))
```

## Relación lineal

```{r}
#| fig-width: 10
#| fig-height: 7
#| fig-align: center
#| lightbox: true
    
texto_le <- paste('y =', round(lm(bbch ~ gdd_log, datos_le)$coefficients[2], 6),
                  'x +', round(lm(bbch ~ gdd_log, datos_le)$coefficients[1], 6),
                  "\n", "R2", " =",
                  round(cor(lm(bbch ~ gdd_log, datos_le)$coefficients[1]+
               lm(bbch ~ gdd_log, datos_le)$coefficients[2]*datos_le$gdd_log,
              datos_le$bbch)^2, 2))

ylim_le <- mean(range(datos_le$bbch))
xlim_le <- max(datos_le$gdd_log)-diff(range(datos_le$gdd_log))*.2

plot_le <- ggplot(datos_le, aes(x = gdd_log, y = bbch)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  geom_text(x = xlim_le, y = ylim_le, label = texto_le, hjust = .5) +
  labs(title = "La Esperanza",
       x = "GDD (log)",
       y = "Escala BBCH") +
  theme_light()

##

texto_rc <- paste('y =', round(lm(bbch ~ gdd_log, datos_rc)$coefficients[2], 6),
                  'x +', round(lm(bbch ~ gdd_log, datos_rc)$coefficients[1], 6),
                  "\n", "R2", " =",
                  round(cor(lm(bbch ~ gdd_log, datos_rc)$coefficients[1]+
               lm(bbch ~ gdd_log, datos_rc)$coefficients[2]*datos_rc$gdd_log,
              datos_rc$bbch)^2, 2))

ylim_rc <- mean(range(datos_rc$bbch))
xlim_rc <- max(datos_rc$gdd_log)-diff(range(datos_rc$gdd_log))*.2

plot_rc <- ggplot(datos_rc, aes(x = gdd_log, y = bbch)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  geom_text(x = xlim_rc, y = ylim_rc, label = texto_rc, hjust = .5) +
  labs(title = "Rio Claro",
       x = "GDD (log)",
       y = "Escala BBCH") +
  theme_light()

plot_grid(ggdraw() + draw_label('Ajuste lineal BBCH vs. GDD (2022-2023)', size = 14),
                          plot_grid(plot_le,plot_rc, ncol = 2),
                          ncol = 1, rel_heights = c(.1,1))
```
